name: Android CI

on:
  push:
    branches:
      - ci-cd
  pull_request:
    branches:
      - ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.0.0'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build Android App
        run: |
          ./gradlew assembleRelease

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute path/to/your/apk.apk --app $FIREBASE_APP_ID --token 1//0gv4Y5fYX3qFjCgYIARAAGBASNwF-L9IraSoip0wWYpHQyCZisn_8MLTw-hSR2OX0YP-Pb475godB8by_v-g8vYcKTLj16aVOsNk
        env:
          FIREBASE_TOKEN: 1//0gv4Y5fYX3qFjCgYIARAAGBASNwF-L9IraSoip0wWYpHQyCZisn_8MLTw-hSR2OX0YP-Pb475godB8by_v-g8vYcKTLj16aVOsNk

#      - name: Set up JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: '11'
#
#      - name: Grant execute permission for Gradlew
#        run: chmod +x ./gradlew
#
#      - name: Build and test
#        run: ./gradlew clean assembleDebug testDebug
#
#      - name: Upload APK
#        uses: actions/upload-artifact@v2
#        with:
#          name: app-debug
#          path: app/build/outputs/apk/debug/app-debug.apk